imports:
    - php

filter:
    paths: [PHPDaemon/*]

tools:
    php_pdepend: true
    php_analyzer: true
    php_sim: true
    # disable copy paste detector and simliarity analyzer as they have no real value
    # and a huge bunch of false-positives
    php_cpd: false

checks:
    php:
        deadlock_detection_in_loops: true
        verify_property_names: true
        verify_argument_usable_as_reference: true
        verify_access_scope_valid: true
        variable_existence: true
        useless_calls: true
        use_statement_alias_conflict: true
        code_rating: true
        duplication: true
        unused_variables: true
        unused_properties: true
        unused_parameters: true
        unused_methods: true
        unreachable_code: true
        sql_injection_vulnerabilities: true
        security_vulnerabilities: true
        precedence_mistakes: true
        precedence_in_conditions: true
        parameter_non_unique: true
        no_property_on_interface: true
        no_non_implemented_abstract_methods: true
        deprecated_code_usage: true
        closure_use_not_conflicting: true
        closure_use_modifiable: true
        avoid_useless_overridden_methods: true
        avoid_conflicting_incrementers: true
        assignment_of_null_return: true
        use_self_instead_of_fqcn: true
        uppercase_constants: true
        uppercase_basic_constants: true
        too_many_arguments: true
        symfony_request_injection: true
        switch_fallthrough_commented: true
        spacing_of_function_arguments: true
        spacing_around_non_conditional_operators: true
        spacing_around_conditional_operators: true
        single_namespace_per_use: true
        simplify_boolean_return: true
        side_effects_or_types: true
        return_doc_comments: true
        return_doc_comment_if_not_inferrable: true
        require_scope_for_properties: true
        require_scope_for_methods: true
        require_braces_around_control_structures: true
        prefer_sapi_constant: true
        php5_style_constructor: true
        parameter_doc_comments: true
        param_doc_comment_if_not_inferrable: true
        no_unnecessary_final_modifier: true
        no_underscore_prefix_in_properties: true
        no_underscore_prefix_in_methods: true
        no_trait_type_hints: true
        no_trailing_whitespace: true
        no_space_inside_cast_operator: true
        no_space_before_semicolon: true
        no_space_around_object_operator: true
        no_space_after_cast: true
        lowercase_php_keywords: true
        lowercase_basic_constants: true
        line_length:
            max_length: '120'
        instanceof_class_exists: true
        function_body_start_on_same_line: true
        foreach_usable_as_reference: true
        blank_line_after_namespace_declaration: true
        avoid_todo_comments: true
        avoid_tab_indentation: true
        avoid_perl_style_comments: true
        avoid_entity_manager_injection: true
        avoid_fixme_comments: true
        argument_type_checks: true
        non_commented_empty_catch_block: true
        no_debug_code: true
        ensure_lower_case_builtin_functions: true
        fix_doc_comments: true
        missing_arguments: true
        method_calls_on_non_object: true
        foreach_traversable: true
        no_duplicate_arguments: true
