<?php
error_reporting(E_ALL);
ini_set('display_errors','1');
return array(
 'mod-http-listen' => 'tcp://0.0.0.0,unix:/tmp/phpfastcgi.sock',
 'mod-http-enable' => 1,
 'mod-fastcgi-enable' => 1,
 'mod-chat-enable' => 1,
 'mod-chat-adminpassword' => 'lolz',
 'mod-mongoclient-enable' => 1,
 //'mod-debugconsole-enable' => 1,
 'mod-telnethoneypot-enable' => 1,
 'mod-flashpolicy-enable' => 1,
 'mod-websocketserver-enable' => 1,
 'mod-websocketovercomet-enable' => 1,
 'max-requests' => 1000,
 'max-idle' => 0,
 'min-spare-workers' => 5,
 'max-spare-workers' => 20,
 'start-workers' => 20,
 'max-workers' => 50,
 'min-workers' => 20,
 'user' => 'web',
 'group' => 'web',
 'path' => dirname(__FILE__).'/appResolver.php',
 //'mpm' => function() {},
 'max-concurrent-requests-per-worker' => 1000,
 'mod-fastcgi-sendfile' => 0,
 'mod-fastcgi-sendfile-dir' => '/shm/',
 'mod-fastcgi-sendfile-prefix' => 'fcgi-',
 'mod-fastcgi-sendfile-only-by-command' => 0,
);
