#!/bin/bash

rm -rf output/*

phpdoc                                                 \
	-d ../                                         \
	-i 'doc/*,applications/*'                      \
	-dn 'Core'                                     \
	-ue on                                         \
	-o HTML:Smarty:PHPDaemon                       \
	-t output/                                     \
	-ti 'PHPDaemon Source Code Documentation'
